### ISSUE TITLE
Is FAISS database retrieval latency really aligned with decode latency?

### ISSUE THREAD

**Issue by right135** [amazon-science/piperag#2]
I built a faiss database of the order of 200 million. I used gpu to retrieve it, which only took 7 milliseconds to complete.
As far as I know, the decode delay should be around 100 milliseconds

**Comment by right135** [comment]
@cheungdaven I'm sorry to bother you. Could you please tell me why CPU is used for retrieval in the paper? This is very important to me. Thank you very much.

**Comment by WenqiJiang** [comment]
> @cheungdaven I'm sorry to bother you. Could you please tell me why CPU is used for retrieval in the paper? This is very important to me. Thank you very much.

CPU is used for retrieval for cost and scalability reasons. For the 3-billion vector dataset we used, it consumes 9TB storage before PQ, and after PQ it can consume anywhere between 100 ~ 500 GB. Note that the original Retro paper uses 64B vectors, so it is practically unaffordable on GPUs (A100 has 40 ~ 80 GB HBM per device) -> the argument of Retro is essentially using very large database + small model to replace large models.

On the other hand, for the Retro checkpoint we used, the latency is 5~10 ms per token (batch size of 1).

**Comment by right135** [comment]
I admit that the database will be very large, but why not chunk the database and perform GPU-based retrieval on chunks? Also, I’m curious about the current submission status of your paper. I would like to base my work on your paper. @WenqiJiang

**Comment by WenqiJiang** [comment]
> I admit that the database will be very large, but why not chunk the database and perform GPU-based retrieval on chunks? Also, I’m curious about the current submission status of your paper. I would like to base my work on your paper. @WenqiJiang

I am not sure Faiss has good support for the hybrid CPU-GPU search you suggested. In case it does, here's my suspicion: at small batch sizes, the GPU might be slightly faster because CPU processes one query per core and it's slow, but at larger batches, the GPU performance is going to be bound by sending the database vectors over PCIe (let's say 32 GB/s, far less than CPU-side memory bandwidth) and thus slower than CPU.

For the paper, it's still under submission.

**Comment by right135** [comment]
Thank you very much for your answer. One last question: For a FAISS database of several hundred GB, the retrieval time using ANN methods should be in the seconds range, right? How did you manage to achieve millisecond-level retrieval times? @WenqiJiang

**Comment by WenqiJiang** [comment]
> Thank you very much for your answer. One last question: For a FAISS database of several hundred GB, the retrieval time using ANN methods should be in the seconds range, right? How did you manage to achieve millisecond-level retrieval times? @WenqiJiang

The ANN search has a fundamental trade-off between latency and recall, and you can control this knob by tuning the amount of database vector to scan. If you only need low quality, it can be done in even tens of ms, but as you mentioned it can go all the way up to more than 1s for better quality.

**Comment by cheungdaven** [comment]
@right135 thanks for raising the question and thank @WenqiJiang for addressing it. I will close this issue if no further actions are required. @right135 please open a new one if you have any other issues, thanks!
